#!/bin/bash

# vim: set filetype=sh

MVNCMD=$(command -v mvn)
if [ -z ${MVNCMD} ] || [ ! -x ${MVNCMD} ]; then
  echo "maven 3.x is required"
  echo "if you use brew do 'brew install maven'"
  exit 127 
fi

if [ -z "$(java -version 2>&1 | grep version | grep 1.8)" ]; then 
  echo "java 8 is required"
  echo "if you use brew do 'brew install java' and setup JAVA_HOME"
  echo "you will be prompted for your password"
  exit 127
fi

RED='\033[0;41;30m'
STD='\033[0;0;39m'

GROUPID=com.mycompany
ARTIFACTID=my-app
VERSION=0.0.1-SNAPSHOT

AAID=jooby-archetype
AGID=org.jooby
AVER=0.1.0

BOOTVER=0.2.2

show_menus() {
  clear
  echo "~~~~~~~~~~~~~~~~~~~~~"  
  echo " M A I N - M E N U"
  echo "~~~~~~~~~~~~~~~~~~~~~"
  echo "1. Choose your project's groupId (default: com.mycompany) current: ${GROUPID}"
  echo "2. Choose your project's artifactId (default: my-app) current: ${ARTIFACTID}"
  echo "3. Choose your project's version (default: 0.0.1-SNAPSHOT) current: ${VERSION}"
  echo "R. Run project"
  echo "G. Generate project"
  echo "Q. Exit"
}

groupid(){
  echo -n "Enter your project's groupId (current: ${GROUPID}) "
  read GROUPID
}

artifactid(){
  echo -n "Enter your project's groupId (current: ${ARTIFACTID}) "
  read ARTIFACTID
}

version(){
  echo -n "Enter your project's version (current: ${VERSION}) "
  read VERSION
}

go(){
  ${MVNCMD} archetype:generate -B -DgroupId=${GROUPID} -DartifactId=${ARTIFACTID} \
    -Dversion=${VERSION} -DarchetypeArtifactId=${AAID} \
    -DarchetypeGroupId=${AGID} -DarchetypeVersion=${AVER}
  exit 0
}

read_options() {
  local choice
  read -p "Enter choice " choice
  case ${choice} in
    1)
      groupid
      ;;
    2)
      artifactid
      ;;
    3)
      version
      ;;
    R|r)
      start_jooby_app
      ;;
    G|g)
      go
      ;;
    Q|q)
      exit 0;;
    *)
      echo -e "${RED}Error...${STD}" && sleep 1
  esac
}

generate_loop() {
  while true
  do
    show_menus
    read_options
  done
}

start_jooby_app() {
  if [ -f "${PWD}/pom.xml" ] && [ ! -z "$(grep org.jooby ${PWD}/pom.xml)" ] ; then
    ${MVNCMD} jooby:run
    exit 0
  else
    echo "not a jooby project"
    exit 1
  fi
}

print_version() {
  echo "bootstrap version: ${BOOTVER}"
}

print_fullversion() {
  print_version
  echo "jooby version: ${AVER}"
}
if [ $# -gt 0 ]; then
  for i in "$@"; do
    case $i in 
      generate)
        generate_loop
        ;;
      help)
        echo "here goes the help"
        ;;
      run)
        start_jooby_app
        ;;
      fullversion)
        print_fullversion
        ;;
      version)
        print_version
        ;;
      *)
        echo "invalid command"
        echo "call help"
        ;;
    esac
  done
else
  generate_loop
fi
